name: Build and Test

on:
  push:
    branches:
      - develop
      - main
      - feature/*
      - hotfix/*
      - release/*
      - bugfix/*

jobs:
  build:
    runs-on: node-alpine
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build

  test:
    runs-on: node-alpine
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn test:e2e

